# Generated by Django 2.1.1 on 2020-05-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalKwMonthly',
            fields=[
                ('meter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('read_month', models.IntegerField()),
                ('read_year', models.IntegerField()),
                ('total_kw', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'vw_total_kw_monthly',
                'managed': False,
            },
        ),
    ]
